### Configfile ###### 
## PERSONAL INFORMATION ##
# Author: Christian Heyer
# Position: PhD Student
# Date: 
# Institution: 

## PROJECT INFORMATION ##
# Name of the project: 
# Phabricator's project: 
# Assigned task (optional):


## SCRIPT INFORMATION ##
# Title: 
# Description: 
#   
# Environments: 
# Dependencies: 
# Usage: use with `snakemake --configfile {this_file}

######

# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
samples: 'data/test_data/coldata.tsv' #### Sample sheet
counts: 'data/test_data/mouse_counts.tsv' # Path to count data
gene_name_type: ENSEMBL # ENSEMBL or HGNC Or ENTREZ_ID
organism: "Mus musculus" # Name of Organsim sequenced (Supported: Mus Musculus, Homo sapiens)

### Data Dirs ###
dirs:
  BASE_DATA_DIR: 'data/test_data'
  BASE_ANALYSIS_DIR: 'data/test_workflow'


## Configuration
pca:
  labels:
    # columns of sample sheet to use for PCA
    - cond

diffexp:
  gsea_use_stat: False
  pval_threshold: 0.05 
  LFC_threshold: 0.5
  shrink_lfc: True
    # contrasts for the deseq2 results method
  contrasts:
    cond: # Here column in sample sheet 
      Del_8_17_homo_vs_wt: # comparison
        - Del_8_17_homo
        - WT
  model: "~cond"
      
## Color control
group_colors:
  cond:
    Del_8_17_homo: "red"
    WT: "blue"

# Workflow control and management
run_mitch: False
run_carnival:
  vanilla: False
  inverse: False
  sample: False  
  joint_rep: False

cplex_solver: ""

DKFZ: False